version: "3.7"

volumes:
  mongodb: {}

services:
  mongodb:
    image : mongo:5.0.9
    container_name: mongodb
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
    - mongodb:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
